//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colosoft.Reflection.Local.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Colosoft.Reflection.Local.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao analisar o assembly &apos;{0}&apos;..
        /// </summary>
        internal static string AssemblyRepository_AnalyzeAssemblyError {
            get {
                return ResourceManager.GetString("AssemblyRepository_AnalyzeAssemblyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly part &apos;{0}&apos; not found..
        /// </summary>
        internal static string AssemblyRepository_AssemblyPartNotFound {
            get {
                return ResourceManager.GetString("AssemblyRepository_AssemblyPartNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly part &apos;{0}&apos; not found..
        /// </summary>
        internal static string AssemblyRepository_AssemblyPartNotFound1 {
            get {
                return ResourceManager.GetString("AssemblyRepository_AssemblyPartNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao recuperar os arquivos para o repositório apartir do diretório &apos;{0}&apos;..
        /// </summary>
        internal static string AssemblyRepository_GetFilesFromRepositoryDirectoryError {
            get {
                return ResourceManager.GetString("AssemblyRepository_GetFilesFromRepositoryDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um ao executar a manuteção do repositório pelo módulo &apos;{0}&apos;.
        ///Detalhes:
        ///{1}.
        /// </summary>
        internal static string AssemblyRepository_MaintenanceError {
            get {
                return ResourceManager.GetString("AssemblyRepository_MaintenanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro e não foi possível validar a entrada do cache do pacote..
        /// </summary>
        internal static string AssemblyRepository_ValidateAssemblyPackageCacheEntryError {
            get {
                return ResourceManager.GetString("AssemblyRepository_ValidateAssemblyPackageCacheEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro e não foi possível validar o pacote de assemblies..
        /// </summary>
        internal static string AssemblyRepository_ValidateAssemblyPackageError {
            get {
                return ResourceManager.GetString("AssemblyRepository_ValidateAssemblyPackageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem erros na execução da manutenção do repositório usando &apos;{0}&apos;..
        /// </summary>
        internal static string AssemblyRepository_ValidateMaintenanceError {
            get {
                return ResourceManager.GetString("AssemblyRepository_ValidateMaintenanceError", resourceCulture);
            }
        }
    }
}
